{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clawsafe.serviceAccountName" . }}
  labels:
    {{- include "clawsafe.labels" . | nindent 4 }}
{{- end }}
